service: controversy-cards

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  environment:
    MLABDB: process.env.MLABDB

functions:
  metacardsList:
    handler: metacards.list
    description: Gets a complete listing of the controversy card collection
    events:
      - http:
          path: metacards
          method: get
          cors: true

  cardsGet:
    handler: cards.get
    description: Gets all information for a specific card, by id
    events:
      - http:
          path: cards/{id}
          method: get
          cors: true     
